-- Insert comprehensive English lessons
INSERT INTO public.lessons (title, slug, description, content, difficulty_level, category, order_index, estimated_time) VALUES
-- Fundamentals
('Database Fundamentals', 'database-fundamentals', 'Understanding databases, DBMS, and relational concepts', '{"sections": [{"title": "What is a Database?", "content": "A database is an organized collection of structured information stored electronically in a computer system, managed by a Database Management System (DBMS)."}, {"title": "Types of Databases", "content": "Relational (SQL), Document (MongoDB), Graph (Neo4j), Key-Value (Redis), and Column-family (Cassandra) databases serve different purposes."}, {"title": "RDBMS Concepts", "content": "Tables, rows, columns, primary keys, foreign keys, and relationships form the foundation of relational databases."}]}', 1, 'Fundamentals', 1, 30),

('Introduction to SQL', 'intro-to-sql', 'SQL basics and core concepts', '{"sections": [{"title": "What is SQL?", "content": "SQL (Structured Query Language) is the standard language for managing and manipulating relational databases."}, {"title": "SQL Categories", "content": "DDL (Data Definition), DML (Data Manipulation), DCL (Data Control), and TCL (Transaction Control) languages."}, {"title": "Basic Syntax", "content": "SQL statements are case-insensitive, end with semicolons, and follow a structured syntax pattern."}]}', 1, 'Fundamentals', 2, 25),

('Table Structure & Data Types', 'table-structure', 'Understanding table design and data types', '{"sections": [{"title": "Table Components", "content": "Tables consist of rows (records) and columns (fields) with defined data types and constraints."}, {"title": "Common Data Types", "content": "INTEGER, VARCHAR, DATE, BOOLEAN, DECIMAL, TEXT, and TIMESTAMP are fundamental SQL data types."}, {"title": "Constraints", "content": "PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, CHECK, and DEFAULT constraints ensure data integrity."}]}', 1, 'Fundamentals', 3, 35),

-- Querying Data
('SELECT Statements', 'select-statements', 'Master data retrieval with SELECT', '{"sections": [{"title": "Basic SELECT", "content": "SELECT column1, column2 FROM table_name; retrieves specific columns from a table."}, {"title": "SELECT ALL", "content": "SELECT * FROM table_name; retrieves all columns from a table."}, {"title": "Column Aliases", "content": "SELECT column1 AS alias1 FROM table_name; creates readable column names in results."}]}', 2, 'Querying', 4, 40),

('Filtering with WHERE', 'where-clause', 'Filter data using WHERE conditions', '{"sections": [{"title": "Basic Filtering", "content": "WHERE clause filters records based on specified conditions before returning results."}, {"title": "Comparison Operators", "content": "=, !=, <>, >, <, >=, <= compare values in WHERE conditions."}, {"title": "Logical Operators", "content": "AND, OR, NOT combine multiple conditions for complex filtering."}]}', 2, 'Querying', 5, 45),

('Sorting with ORDER BY', 'order-by', 'Sort query results effectively', '{"sections": [{"title": "Basic Sorting", "content": "ORDER BY sorts results by one or more columns in ascending or descending order."}, {"title": "ASC and DESC", "content": "ASC (ascending) is default, DESC sorts in descending order."}, {"title": "Multiple Columns", "content": "ORDER BY col1 ASC, col2 DESC sorts by multiple criteria with different directions."}]}', 2, 'Querying', 6, 35),

-- Functions & Aggregation
('Aggregate Functions', 'aggregate-functions', 'COUNT, SUM, AVG, MIN, MAX functions', '{"sections": [{"title": "COUNT Function", "content": "COUNT(*) counts all rows, COUNT(column) counts non-NULL values in a column."}, {"title": "Mathematical Functions", "content": "SUM() calculates totals, AVG() computes averages for numeric columns."}, {"title": "MIN and MAX", "content": "MIN() finds smallest values, MAX() finds largest values in a column."}]}', 3, 'Functions', 7, 50),

('GROUP BY & HAVING', 'group-by-having', 'Group data and filter groups', '{"sections": [{"title": "GROUP BY Basics", "content": "GROUP BY groups rows with identical values in specified columns for aggregation."}, {"title": "HAVING Clause", "content": "HAVING filters groups created by GROUP BY, similar to WHERE for individual rows."}, {"title": "Grouping Rules", "content": "All non-aggregate columns in SELECT must appear in GROUP BY clause."}]}', 3, 'Functions', 8, 55),

-- Joins
('INNER JOIN', 'inner-join', 'Combine tables with INNER JOIN', '{"sections": [{"title": "JOIN Concept", "content": "JOINs combine rows from multiple tables based on related columns between them."}, {"title": "INNER JOIN", "content": "INNER JOIN returns only rows with matching values in both tables."}, {"title": "JOIN Syntax", "content": "SELECT columns FROM table1 INNER JOIN table2 ON table1.column = table2.column;"}]}', 4, 'Joins', 9, 60),

('OUTER JOINs', 'outer-joins', 'LEFT, RIGHT, and FULL OUTER JOINs', '{"sections": [{"title": "LEFT JOIN", "content": "LEFT JOIN returns all rows from left table and matching rows from right table."}, {"title": "RIGHT JOIN", "content": "RIGHT JOIN returns all rows from right table and matching rows from left table."}, {"title": "FULL OUTER JOIN", "content": "FULL OUTER JOIN returns all rows when there is a match in either table."}]}', 4, 'Joins', 10, 65),

-- Advanced Topics
('Subqueries', 'subqueries', 'Nested queries and subqueries', '{"sections": [{"title": "Subquery Basics", "content": "A subquery is a query nested inside another query, executed first to provide results to the outer query."}, {"title": "Scalar Subqueries", "content": "Scalar subqueries return single values and can be used anywhere a single value is expected."}, {"title": "IN and EXISTS", "content": "IN checks if a value exists in subquery results, EXISTS checks if subquery returns any rows."}]}', 5, 'Advanced', 11, 70),

('Window Functions', 'window-functions', 'ROW_NUMBER, RANK, and analytical functions', '{"sections": [{"title": "Window Function Concept", "content": "Window functions perform calculations across related rows without grouping the result set."}, {"title": "ROW_NUMBER and RANK", "content": "ROW_NUMBER() assigns unique numbers, RANK() handles ties by giving same rank to equal values."}, {"title": "PARTITION BY", "content": "PARTITION BY divides result set into partitions for window function calculations."}]}', 5, 'Advanced', 12, 80),

-- Data Modification
('INSERT Statements', 'insert-data', 'Adding new records to tables', '{"sections": [{"title": "Basic INSERT", "content": "INSERT INTO table_name (columns) VALUES (values) adds new records to tables."}, {"title": "Multiple Inserts", "content": "INSERT INTO table_name VALUES (row1), (row2), (row3) inserts multiple rows efficiently."}, {"title": "INSERT with SELECT", "content": "INSERT INTO table1 SELECT columns FROM table2 WHERE condition; copies data between tables."}]}', 2, 'Data Modification', 13, 40),

('UPDATE Statements', 'update-data', 'Modifying existing records', '{"sections": [{"title": "Basic UPDATE", "content": "UPDATE table_name SET column1 = value1 WHERE condition modifies existing records."}, {"title": "Multiple Columns", "content": "UPDATE table_name SET col1 = val1, col2 = val2 WHERE condition updates multiple columns."}, {"title": "UPDATE Safety", "content": "Always use WHERE clause with UPDATE to avoid modifying all rows accidentally."}]}', 2, 'Data Modification', 14, 35),

('DELETE Statements', 'delete-data', 'Removing records from tables', '{"sections": [{"title": "Basic DELETE", "content": "DELETE FROM table_name WHERE condition removes specific records from tables."}, {"title": "DELETE vs TRUNCATE", "content": "DELETE removes specific rows, TRUNCATE removes all rows and resets identity columns."}, {"title": "DELETE Safety", "content": "Always use WHERE clause with DELETE to avoid removing all data accidentally."}]}', 2, 'Data Modification', 15, 30),

-- Database Design
('CREATE TABLE', 'create-table', 'Creating database tables', '{"sections": [{"title": "CREATE TABLE Syntax", "content": "CREATE TABLE table_name (column1 datatype constraints, column2 datatype constraints) defines new tables."}, {"title": "Column Constraints", "content": "PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, CHECK, DEFAULT ensure data integrity."}, {"title": "Table Relationships", "content": "Foreign keys create relationships between tables, enforcing referential integrity."}]}', 3, 'Database Design', 16, 50),

('Indexes & Performance', 'indexes-performance', 'Optimizing query performance', '{"sections": [{"title": "Index Basics", "content": "Indexes speed up data retrieval by creating shortcuts to table data, like book indexes."}, {"title": "Index Types", "content": "Clustered indexes physically order data, non-clustered indexes point to data locations."}, {"title": "Performance Impact", "content": "Indexes speed up SELECT queries but slow down INSERT, UPDATE, DELETE operations."}]}', 4, 'Performance', 17, 60),

-- Business Intelligence
('Analytical Queries', 'analytical-queries', 'Business intelligence and reporting', '{"sections": [{"title": "Reporting Queries", "content": "Analytical queries aggregate and summarize data for business insights and decision making."}, {"title": "Time-based Analysis", "content": "Date functions and time periods enable trend analysis and temporal reporting."}, {"title": "KPI Calculations", "content": "Key Performance Indicators use SQL aggregations to measure business metrics."}]}', 4, 'Business Intelligence', 18, 70),

('Data Warehousing', 'data-warehousing', 'ETL processes and data modeling', '{"sections": [{"title": "Data Warehouse Concepts", "content": "Data warehouses store historical data from multiple sources for analytical processing."}, {"title": "ETL Processes", "content": "Extract, Transform, Load processes move and clean data from operational systems to warehouses."}, {"title": "Dimensional Modeling", "content": "Star and snowflake schemas organize data for efficient analytical queries."}]}', 5, 'Business Intelligence', 19, 85),

-- Security & Administration
('Database Security', 'database-security', 'User management and access control', '{"sections": [{"title": "User Authentication", "content": "Database users require proper authentication and authorization for secure access."}, {"title": "Permissions & Roles", "content": "GRANT and REVOKE statements control user permissions on database objects."}, {"title": "SQL Injection Prevention", "content": "Parameterized queries and input validation prevent SQL injection attacks."}]}', 4, 'Security', 20, 55);